name: 'Linting'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  super-linter:
    name: 'SuperLinter'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint Code Base
      uses: github/super-linter/slim@v5.0.0
      env:
        # https://github.com/github/super-linter#environment-variables
        VALIDATE_TERRAFORM_FMT: true
        VALIDATE_TERRAFORM_TFLINT: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
